version: '3.8'

services:
  app:
    build: .
    container_name: fraud-app
    ports:
      - "9090:9090"
    depends_on:
      - db
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/frauddb
      SPRING_DATASOURCE_USERNAME: frauduser
      SPRING_DATASOURCE_PASSWORD: fraudpass
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - fraudnet

  db:
    image: postgres:15
    container_name: fraud-db
    environment:
      POSTGRES_DB: frauddb
      POSTGRES_USER: frauduser
      POSTGRES_PASSWORD: fraudpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - fraudnet

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - fraudnet

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms128M"
    depends_on:
      - zookeeper
    networks:
      - fraudnet

volumes:
  pgdata:

networks:
  fraudnet:
