version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus-local
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana-local
    ports:
      - "3000:3000"
    restart: always
